# Generated by Django 4.1.5 on 2023-01-30 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.CharField(max_length=500, null=True)),
                ('f_name', models.CharField(max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('birth_dt', models.DateField(null=True)),
                ('is_worker', models.BooleanField(default=False, verbose_name='worker status')),
                ('is_client', models.BooleanField(default=False, verbose_name='client status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gps_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jib', models.AutoField(primary_key=True, serialize=False)),
                ('occupation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('expiration_dt', models.DateField()),
                ('cvv', models.IntegerField()),
                ('funds', models.IntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='worker', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avg_rating', models.CharField(max_length=100)),
                ('avaliable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=100)),
                ('descrpition', models.CharField(max_length=500)),
                ('card_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_num_service', to='mande_api.payment_method')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jid_service', to='mande_api.job')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_service', to='mande_api.client')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_id_service', to='mande_api.worker')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_id_user', to='mande_api.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_id_user', to='mande_api.gps_location'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Worker_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jid_worker', to='mande_api.job')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_id_job', to='mande_api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_img_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_img_data', models.ImageField(upload_to='imagenesCedula/')),
                ('prof_img_data', models.ImageField(upload_to='imagenesPerfil/')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_id_imgdata', to='mande_api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('receipt_data', models.CharField(max_length=200)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_receipt', to='mande_api.client')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('hid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sid_history', to='mande_api.service')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_history', to='mande_api.client')),
            ],
        ),
    ]
