# Generated by Django 4.1.3 on 2023-02-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='avaliable',
            new_name='available',
        ),
    ]
