# Generated by Django 4.1.3 on 2023-02-02 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_location',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_id_gps', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
