# Generated by Django 4.1.3 on 2023-02-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='hid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
