# Generated by Django 4.1.3 on 2023-02-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0002_alter_gps_location_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='occupation',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
