# Generated by Django 4.1.3 on 2023-02-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0002_alter_history_hid_alter_receipt_rid_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_data',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='worker_job',
            name='jid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jid_worker', to='mande_api.job', unique=True),
        ),
        migrations.AlterField(
            model_name='worker_job',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_id_job', to='mande_api.worker', unique=True),
        ),
    ]
