# Generated by Django 4.1.3 on 2023-02-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0002_rename_avaliable_worker_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descrpition',
            new_name='descripition',
        ),
    ]
