# Generated by Django 4.1.3 on 2023-02-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0003_rename_descrpition_service_descripition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descripition',
            new_name='description',
        ),
    ]
