# Generated by Django 4.1.3 on 2023-02-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0003_alter_job_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='jid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_id_user', to='mande_api.job'),
        ),
    ]
