# Generated by Django 4.1.3 on 2023-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0004_rename_descripition_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_location',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='gps_location',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
    ]
