# Generated by Django 4.1.3 on 2023-02-03 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0005_alter_gps_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='sid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sid_history', to='mande_api.service'),
        ),
    ]
