# Generated by Django 4.1.3 on 2023-02-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0005_alter_receipt_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_receipt', to='mande_api.client'),
        ),
        migrations.AlterField(
            model_name='worker_img_data',
            name='worker_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_id_imgdata', to='mande_api.worker'),
        ),
    ]
