# Generated by Django 4.1.3 on 2023-02-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0006_alter_history_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='j_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
