# Generated by Django 4.1.3 on 2023-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande_api', '0007_job_j_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='Aceptado', max_length=200),
        ),
    ]
